import type { Property, Hostel } from "./types";
type BookingRequest = any;

// Using Unsplash source URLs for realistic placeholder images
const homeImages = [
  "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
  "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80",
  "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
  "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
  "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
  "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80",
];

const interiorImages = [
  "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
  "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&q=80",
  "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
  "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80",
  "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80",
  "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80",
];

const hostelImages = [
  "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80",
  "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&q=80",
  "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80",
  "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80",
];

export const mockHomes: Property[] = [
  {
    id: "home-1",
    type: "home",
    propertyType: "apartment",
    title: "Modern 3-Bedroom Flat",
    description:
      "Spacious, well-finished 3-bedroom apartment in a serene estate. 24/7 security, ample parking, and a backup generator. Minutes from the expressway.",
    price: 4500,
    priceLabel: "₵4,500/mo",
    forSale: false,
    beds: 3,
    baths: 2,
    sqft: 1400,
    address: "14 Orchid Road, East Legon",
    city: "Accra",
    state: "Greater Accra",
    images: [homeImages[0], interiorImages[0], interiorImages[1], interiorImages[2]],
    amenities: ["Generator", "Security", "Parking", "AC"],
    ownerPhone: "+233201234567",
    ownerId: "owner-1",
  },
  {
    id: "home-2",
    type: "home",
    propertyType: "house",
    title: "4-Bed Detached Duplex",
    description:
      "Tastefully built 4-bedroom detached duplex with boys' quarters, spacious compound, and fitted kitchen. Great for a growing family.",
    price: 7500,
    priceLabel: "₵7,500/mo",
    forSale: false,
    beds: 4,
    baths: 3,
    sqft: 2200,
    address: "7 Harmony Close, Airport Residential",
    city: "Accra",
    state: "Greater Accra",
    images: [homeImages[1], interiorImages[0], interiorImages[4], interiorImages[1]],
    amenities: ["Generator", "Security", "Parking", "Boys Quarters", "Fitted Kitchen"],
    ownerPhone: "+233202345678",
    ownerId: "owner-2",
  },
  {
    id: "home-3",
    type: "home",
    propertyType: "studio",
    title: "Cozy Studio Apartment",
    description:
      "A sleek self-contained studio with air-conditioning, fitted wardrobe, and constant water supply. Perfect for a working professional.",
    price: 1500,
    priceLabel: "₵1,500/mo",
    forSale: false,
    beds: 1,
    baths: 1,
    sqft: 480,
    address: "22 Adum Road",
    city: "Kumasi",
    state: "Ashanti",
    images: [homeImages[2], interiorImages[1], interiorImages[2], interiorImages[3]],
    amenities: ["AC", "Water Supply", "Wardrobe"],
    ownerPhone: "+233203456789",
    ownerId: "owner-3",
  },
  {
    id: "home-4",
    type: "home",
    propertyType: "apartment",
    title: "2-Bedroom Serviced Apartment",
    description:
      "Fully-serviced 2-bedroom apartment in a gated community. Includes electricity, water, and cleaning service. Move-in ready.",
    price: 3200,
    priceLabel: "₵3,200/mo",
    forSale: false,
    beds: 2,
    baths: 2,
    sqft: 1050,
    address: "Plot 5 Liberation Road, Adabraka",
    city: "Accra",
    state: "Greater Accra",
    images: [homeImages[3], interiorImages[0], interiorImages[1], interiorImages[2]],
    amenities: ["Generator", "Security", "Cleaning Service", "AC", "Gated Estate"],
    ownerPhone: "+233204567890",
    ownerId: "owner-4",
  },
  {
    id: "home-5",
    type: "home",
    propertyType: "duplex",
    title: "Semi-Detached 5-Bedroom Home",
    description:
      "Grand 5-bedroom semi-detached home with smart home features, rooftop terrace, and a private garden. A rare gem.",
    price: 850000,
    priceLabel: "₵850,000",
    forSale: true,
    beds: 5,
    baths: 4,
    sqft: 3800,
    address: "1 Marina Drive, Cantonments",
    city: "Accra",
    state: "Greater Accra",
    images: [homeImages[4], interiorImages[0], interiorImages[1], interiorImages[5]],
    amenities: ["Smart Home", "Rooftop Terrace", "Garden", "Security", "Generator", "AC"],
    ownerPhone: "+233205678901",
    ownerId: "owner-5",
  },
  {
    id: "home-6",
    type: "home",
    propertyType: "townhouse",
    title: "Luxury Townhouse with Pool",
    description:
      "3-storey luxury townhouse with private pool, home cinema, and 3-car garage. Located in one of Accra's most prestigious estates.",
    price: 1200000,
    priceLabel: "₵1,200,000",
    forSale: true,
    beds: 5,
    baths: 5,
    sqft: 5000,
    address: "Block B, Roman Ridge Estate",
    city: "Accra",
    state: "Greater Accra",
    images: [homeImages[5], interiorImages[0], interiorImages[1], interiorImages[4]],
    amenities: ["Pool", "Home Cinema", "3-Car Garage", "Generator", "Security", "AC", "Garden"],
    ownerPhone: "+233206789012",
    ownerId: "owner-6",
  },
];

export const mockHostels: Hostel[] = [
  {
    id: "hostel-1",
    type: "hostel",
    name: "Greenfield Student Lodge",
    description:
      "Secure, well-maintained hostel a 5-minute walk from the main gate of UG. Known for steady power and fast WiFi.",
    address: "12 University Road, Legon",
    city: "Accra",
    state: "Greater Accra",
    nearbyUniversities: ["University of Ghana (UG)", "GIMPA"],
    images: [hostelImages[0], hostelImages[1]],
    totalRooms: 40,
    availableRooms: 14,
    priceRange: { min: 1800, max: 3500 },
    priceRangeLabel: "₵1,800 – ₵3,500/yr",
    amenities: ["WiFi", "Generator", "Security", "Hot Water", "AC"],
    managerPhone: "+233207123456",
    managerId: "manager-1",
    rooms: [
      {
        id: "room-g1-1",
        hostelId: "hostel-1",
        name: "Room 1A — Single",
        roomType: "single",
        price: 3500,
        priceLabel: "₵3,500/yr",
        capacity: 1,
        available: true,
        amenities: ["wifi", "ac", "attached-bath", "hot-water", "study-desk", "wardrobe", "security", "generator"],
        images: [hostelImages[2], hostelImages[3]],
        description: "Private single room with en-suite bathroom and air-conditioning. Quiet wing of the building.",
      },
      {
        id: "room-g1-2",
        hostelId: "hostel-1",
        name: "Room 2B — Double",
        roomType: "double",
        price: 2500,
        priceLabel: "₵2,500/yr",
        capacity: 2,
        available: true,
        amenities: ["wifi", "hot-water", "study-desk", "wardrobe", "security", "generator"],
        images: [hostelImages[1], hostelImages[2]],
        description: "Shared double room with two study desks. Shared corridor bathrooms. Great value.",
      },
      {
        id: "room-g1-3",
        hostelId: "hostel-1",
        name: "Room 5C — Triple",
        roomType: "triple",
        price: 2000,
        priceLabel: "₵2,000/yr",
        capacity: 3,
        available: false,
        amenities: ["wifi", "study-desk", "wardrobe", "security"],
        images: [hostelImages[0]],
        description: "3-person room with individual lockers. Currently fully occupied.",
      },
      {
        id: "room-g1-4",
        hostelId: "hostel-1",
        name: "Room 8D — Dormitory",
        roomType: "dormitory",
        price: 1800,
        priceLabel: "₵1,800/yr",
        capacity: 8,
        available: true,
        amenities: ["wifi", "security", "generator"],
        images: [hostelImages[1]],
        description: "8-bed dormitory room. Most affordable option. Shared bathroom and kitchen facilities.",
      },
    ],
  },
  {
    id: "hostel-2",
    type: "hostel",
    name: "Summit Crest Hostel",
    description:
      "Premium student accommodation near KNUST. Features a study hall, restaurant, and 24/7 CCTV surveillance.",
    address: "3 University Post Office Road, KNUST",
    city: "Kumasi",
    state: "Ashanti",
    nearbyUniversities: ["KNUST", "Kumasi Technical University"],
    images: [hostelImages[1], hostelImages[2]],
    totalRooms: 60,
    availableRooms: 22,
    priceRange: { min: 2200, max: 4200 },
    priceRangeLabel: "₵2,200 – ₵4,200/yr",
    amenities: ["WiFi", "AC", "Generator", "CCTV", "Security", "Meal Included", "Study Hall"],
    managerPhone: "+233208234567",
    managerId: "manager-2",
    rooms: [
      {
        id: "room-s2-1",
        hostelId: "hostel-2",
        name: "Block A — Executive Single",
        roomType: "single",
        price: 4200,
        priceLabel: "₵4,200/yr",
        capacity: 1,
        available: true,
        amenities: ["wifi", "ac", "attached-bath", "hot-water", "study-desk", "wardrobe", "balcony", "meal-included", "security", "cctv", "generator"],
        images: [hostelImages[2], hostelImages[3]],
        description: "Top-tier single room with balcony, en-suite, and daily meal plan.",
      },
      {
        id: "room-s2-2",
        hostelId: "hostel-2",
        name: "Block B — Standard Double",
        roomType: "double",
        price: 2800,
        priceLabel: "₵2,800/yr",
        capacity: 2,
        available: true,
        amenities: ["wifi", "ac", "hot-water", "study-desk", "wardrobe", "security", "cctv", "generator"],
        images: [hostelImages[0], hostelImages[1]],
        description: "Air-conditioned double room with shared corridor bathrooms. Very popular — book early.",
      },
      {
        id: "room-s2-3",
        hostelId: "hostel-2",
        name: "Block C — Quad Room",
        roomType: "quad",
        price: 2200,
        priceLabel: "₵2,200/yr",
        capacity: 4,
        available: true,
        amenities: ["wifi", "study-desk", "wardrobe", "laundry", "security", "cctv"],
        images: [hostelImages[3]],
        description: "4-person room with in-house laundry access. Budget-friendly with essential amenities.",
      },
    ],
  },
  {
    id: "hostel-3",
    type: "hostel",
    name: "Horizon Hall",
    description:
      "Modern purpose-built hostel blocks directly opposite UCC main campus. High-speed internet, standby generator, and a rooftop chill area.",
    address: "UCC Campus Road, Cape Coast",
    city: "Cape Coast",
    state: "Central",
    nearbyUniversities: ["University of Cape Coast (UCC)"],
    images: [hostelImages[2], hostelImages[3]],
    totalRooms: 80,
    availableRooms: 31,
    priceRange: { min: 1600, max: 3800 },
    priceRangeLabel: "₵1,600 – ₵3,800/yr",
    amenities: ["WiFi", "Generator", "CCTV", "Security", "Laundry", "Rooftop"],
    managerPhone: "+233209345678",
    managerId: "manager-3",
    rooms: [
      {
        id: "room-h3-1",
        hostelId: "hostel-3",
        name: "Block 1 — Self-Contained Single",
        roomType: "single",
        price: 3800,
        priceLabel: "₵3,800/yr",
        capacity: 1,
        available: true,
        amenities: ["wifi", "ac", "attached-bath", "hot-water", "study-desk", "wardrobe", "security", "cctv", "generator"],
        images: [hostelImages[3], hostelImages[0]],
        description: "Fully self-contained single room. Your own space, your own rules.",
      },
      {
        id: "room-h3-2",
        hostelId: "hostel-3",
        name: "Block 2 — Shared Double",
        roomType: "double",
        price: 2400,
        priceLabel: "₵2,400/yr",
        capacity: 2,
        available: false,
        amenities: ["wifi", "study-desk", "wardrobe", "security", "generator"],
        images: [hostelImages[1]],
        description: "Comfortable double room. Currently occupied but will be available next session.",
      },
      {
        id: "room-h3-3",
        hostelId: "hostel-3",
        name: "Block 3 — Triple Room",
        roomType: "triple",
        price: 1950,
        priceLabel: "₵1,950/yr",
        capacity: 3,
        available: true,
        amenities: ["wifi", "study-desk", "wardrobe", "laundry", "security"],
        images: [hostelImages[2]],
        description: "Spacious triple room with laundry access. Great if you're moving in with friends.",
      },
      {
        id: "room-h3-4",
        hostelId: "hostel-3",
        name: "Block 4 — Budget Dormitory",
        roomType: "dormitory",
        price: 1600,
        priceLabel: "₵1,600/yr",
        capacity: 6,
        available: true,
        amenities: ["wifi", "security", "generator"],
        images: [hostelImages[0]],
        description: "6-bed dormitory. The most affordable option on campus. Basic but clean.",
      },
    ],
  },
];

export const mockBookingRequests: BookingRequest[] = [
  {
    id: "booking-1",
    roomId: "room-g1-1",
    hostelId: "hostel-1",
    roomName: "Room 1A — Single",
    hostelName: "Greenfield Student Lodge",
    studentName: "Ama Owusu",
    studentEmail: "ama.owusu@students.ug.edu.gh",
    studentPhone: "+233208123456",
    priceLabel: "₵3,500/yr",
    verificationStatus: "student-email-verified",
    paymentStatus: "unpaid",
    createdAt: "2026-03-08T10:30:00Z",
    expiresAt: "2026-03-08T12:30:00Z",
  },
  {
    id: "booking-2",
    roomId: "room-s2-2",
    hostelId: "hostel-2",
    roomName: "Block B — Standard Double",
    hostelName: "Summit Crest Hostel",
    studentName: "Kwame Mensah",
    studentEmail: "kwame.mensah@knust.edu.gh",
    studentPhone: "+233209234567",
    priceLabel: "₵2,800/yr",
    verificationStatus: "id-pending",
    paymentStatus: "unpaid",
    createdAt: "2026-03-08T09:15:00Z",
    expiresAt: "2026-03-08T11:15:00Z",
  },
  {
    id: "booking-3",
    roomId: "room-h3-1",
    hostelId: "hostel-3",
    roomName: "Block 1 — Self-Contained Single",
    hostelName: "Horizon Hall",
    studentName: "Efua Asante",
    studentEmail: "efua.asante@ucc.edu.gh",
    studentPhone: "+233201345678",
    priceLabel: "₵3,800/yr",
    verificationStatus: "id-verified",
    paymentStatus: "paid",
    createdAt: "2026-03-07T14:00:00Z",
    expiresAt: "2026-03-07T16:00:00Z",
  },
];
